# Enable C++ support

matrix:
  include:
    - os: linux
      language: csharp
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
          packages:
          - clang-3.8
          - qt5-default
          - qttools5-dev-tools
    
    - os: linux
      language: csharp
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
          packages:
          - g++-6
          - qt5-default
          - qttools5-dev-tools
    
    - os: osx
      language: csharp
      compiler: clang
  
    - os: windows
      language: cpp
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/opt/qt/bin:$PATH; fi
  
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
  
# Build steps
script:
  #- ./build_linux.sh
  - echo "$CXX"
  - echo "$TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./build_linux.sh    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cl     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then csc     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then msbuild     ; fi
  - cd
  - pwd
  - cd CsLisp
  - msbuild
  - msbuild /p:Configuration=Release CsLisp.sln
  - ls -lrt
  - cd bin
  - cd Release
  - chmod +x fuel.exe
  - ls -lrt
  - mono ./fuel.exe -v
  - mono ./fuel  -e \"(println (platform))\"
  - cl 
