# Enable C++ support
language: cpp

os:
  - linux
  - osx
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi
  
# Compiler selection
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
    - qt5-default
    - qttools5-dev-tools

install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
  
# Build steps
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo $PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/opt/qt/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo $PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ls -lrt /usr/local/opt/qt/bin; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd CppLisp/CppLispInterpreter; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/opt/qt/bin/qmake -v; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/opt/qt/bin/qmake CppLispInterpreter.pro; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./fuel -v; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build_linux.sh ; fi
  - qmake -v
  - ./build_linux.sh
  
  