# Enable C++ support
language: csharp

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
          packages:
          - clang-3.8
          - qt5-default
          - qttools5-dev-tools
    
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
          packages:
          - g++-6
          - qt5-default
          - qttools5-dev-tools
    
    - os: osx
      compiler: clang
  
    - os: windows
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/opt/qt/bin:$PATH; fi
  
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
  
# Build steps
script:
  #- ./build_linux.sh
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./build_linux.sh    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cl     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then csc     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then msbuild     ; fi
  - cd CsLisp
  - msbuild /p:Configuration=Release CsLisp.sln
  - cd Release
  - ./fuel -v
  - ./fuel.exe -v
  - csc
