# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8

install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
  
# Build steps
script:
  - pwd
  - ls -lrt 
  - ./build_linux.sh
  - gcc -v
  
  