# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

#install:
#  - sudo apt-get install -y qt5-default qttools5-dev-tools
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
    - qt5-default
    - qttools5-dev-tools

install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
  
# Build steps
script:
  - qmake -v
  - ./build_linux.sh
  
  